name: Action Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-great: harsha
      - name: Grt the output timw
        run: echo"${{ steps.hello.outputs.time}}"
